### ISSUE TITLE
MJSXJ02CM at Hassio

### ISSUE THREAD

**Issue by Rtamagnini** [telmomarques/xiaomi-360-1080p-hacks#72]
hello,  I was able to easily downgrade my camera's firmware and hack.
via browser I put:
-enable RTSP and Websocket Stream
-Encoding type: H264
-Enable SSH / SFTP
-created a new username / password

now I see the camera with the address: "rtsp: //192.168.1.104: 8554 / mainstream" and "rtsp://192.168.1.104:8554/substream"

can you tell me what I have to do now to be able to see the camera on Hassio (rpi3)?

do I need to open any ports on my router? 
what instruction to put in yaml?

something like this ?
camera:
  - name: room
    platform: ffmpeg
    stream_source: "rtsp://admin:123456@192.168.1.104:554/h264Preview_01_main"  

Thanks in advance
Ricardo

**Comment by Rtamagnini** [comment]
I also noticed that if I put the encoding on the h264 I no longer have an image on the Mi home app

**Comment by Vorlex** [comment]
@Rtamagnini 
Here's configuration:
```
camera:
  - platform: generic
    name: Xiaomi 360
    stream_source: rtsp: //192.168.1.104: 8554/mainstream
    still_image_url: http://127.0.0.1:8123/local/camera.jpg
```
There is [integration guide](https://www.home-assistant.io/integrations/generic/) for generic camera where you can read more about it. 
Also, this camera doesn't provide static image. You can follow [these steps](https://community.home-assistant.io/t/camera-generic-set-still-image-url-to-local-file/130351/6?u=vorlex) to add custom image as preview on lovelace dashboard.
